//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyExamDBEntities : DbContext
    {
        public MyExamDBEntities()
            : base("name=MyExamDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LoginTB> LoginTBs { get; set; }
        public DbSet<OrderDetailsTB> OrderDetailsTBs { get; set; }
        public DbSet<StockInfoTB> StockInfoTBs { get; set; }
    }
}
