//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsTB
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<System.DateTime> ODate { get; set; }
        public Nullable<int> Purchase_Quantity { get; set; }
    }
}
